version: 2.1

jobs:
  build:
    docker:
      - image: cimg/php:8.1
    steps:
      - run:
          name: Disable XDebug
          command: |
            sudo sed -i 's/^zend_extension/;zend_extension/g' /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
